#pragma once

#define NUM_OPCODES	0x98 //151 opcodes + ".db"

typedef enum
	{
	IMMEDIATE = 0,
	ABSOLUTE,
	ZERO_PAGE,
	IMPLIED,
	INDIRECT_ABSOLUTE,
	ABSOLUTE_INDEXED_X,
	ABSOLUTE_INDEXED_Y,
	ZERO_PAGE_INDEXED_X,
	ZERO_PAGE_INDEXED_Y,
	INDEXED_INDIRECT_X,
	INDIRECT_INDEXED_Y,
	RELATIVE,
	ACCUMULATOR
	} __enAddressingMode;

typedef struct
	{
	unsigned char		ucByte;
	const char			*szName;
	__enAddressingMode	_enAddressingMode;
	} __Opcode;

static	__Opcode		_Opcodes[NUM_OPCODES] =
	{
	//	{0xFF, ".byte", ABSOLUTE},

		{0x61, "ADC", INDEXED_INDIRECT_X},
		{0x65, "ADC", ZERO_PAGE},
		{0x69, "ADC", IMMEDIATE},
		{0x6D, "ADC", ABSOLUTE},
		{0x71, "ADC", INDIRECT_INDEXED_Y},
		{0x75, "ADC", ZERO_PAGE_INDEXED_X},
		{0x79, "ADC", ABSOLUTE_INDEXED_Y},
		{0x7D, "ADC", ABSOLUTE_INDEXED_X},

		{0x21, "AND", INDEXED_INDIRECT_X},
		{0x25, "AND", ZERO_PAGE},
		{0x29, "AND", IMMEDIATE},
		{0x2D, "AND", ABSOLUTE},
		{0x31, "AND", INDIRECT_INDEXED_Y},
		{0x35, "AND", ZERO_PAGE_INDEXED_X},
		{0x39, "AND", ABSOLUTE_INDEXED_Y},
		{0x3D, "AND", ABSOLUTE_INDEXED_X},

		{0x06, "ASL", ZERO_PAGE},
		{0x0A, "ASL", ACCUMULATOR},
		{0x0E, "ASL", ABSOLUTE},
		{0x16, "ASL", ZERO_PAGE_INDEXED_X},
		{0x1E, "ASL", ABSOLUTE_INDEXED_X},

		{0x90, "BCC", RELATIVE},

		{0xB0, "BCS", RELATIVE},

		{0xF0, "BEQ", RELATIVE},

		{0x24, "BIT", ZERO_PAGE},
		{0x2C, "BIT", ABSOLUTE},

		{0x30, "BMI", RELATIVE},

		{0xD0, "BNE", RELATIVE},

		{0x10, "BPL", RELATIVE},

		{0x00, "BRK", IMPLIED},

		{0x50, "BVC", RELATIVE},

		{0x70, "BVS", RELATIVE},

		{0x18, "CLC", IMPLIED},

		{0xD8, "CLD", IMPLIED},

		{0x58, "CLI", IMPLIED},

		{0xB8, "CLV", IMPLIED},

		{0xC1, "CMP", INDEXED_INDIRECT_X},
		{0xC5, "CMP", ZERO_PAGE},
		{0xC9, "CMP", IMMEDIATE},
		{0xCD, "CMP", ABSOLUTE},
		{0xD1, "CMP", INDIRECT_INDEXED_Y},
		{0xD5, "CMP", ZERO_PAGE_INDEXED_X},
		{0xD9, "CMP", ABSOLUTE_INDEXED_Y},
		{0xDD, "CMP", ABSOLUTE_INDEXED_X},

		{0xE0, "CPX", IMMEDIATE},
		{0xE4, "CPX", ZERO_PAGE},
		{0xEC, "CPX", ABSOLUTE},

		{0xC0, "CPY", IMMEDIATE},
		{0xC4, "CPY", ZERO_PAGE},
		{0xCC, "CPY", ABSOLUTE},

		{0xC6, "DEC", ZERO_PAGE},
		{0xCE, "DEC", ABSOLUTE},
		{0xD6, "DEC", ZERO_PAGE_INDEXED_X},
		{0xDE, "DEC", ABSOLUTE_INDEXED_X},

		{0xCA, "DEX", IMPLIED},

		{0x88, "DEY", IMPLIED},

		{0x41, "EOR", INDEXED_INDIRECT_X},
		{0x45, "EOR", ZERO_PAGE},
		{0x49, "EOR", IMMEDIATE},
		{0x4D, "EOR", ABSOLUTE},
		{0x51, "EOR", INDIRECT_INDEXED_Y},
		{0x55, "EOR", ZERO_PAGE_INDEXED_X},
		{0x59, "EOR", ABSOLUTE_INDEXED_Y},
		{0x5D, "EOR", ABSOLUTE_INDEXED_X},

		{0xE6, "INC", ZERO_PAGE},
		{0xEE, "INC", ABSOLUTE},
		{0xF6, "INC", ZERO_PAGE_INDEXED_X},
		{0xFE, "INC", ABSOLUTE_INDEXED_X},

		{0xE8, "INX", IMPLIED},

		{0xC8, "INY", IMPLIED},

		{0x4C, "JMP", ABSOLUTE},
		{0x6C, "JMP", INDIRECT_ABSOLUTE},

		{0x20, "JSR", ABSOLUTE},

		{0xA1, "LDA", INDEXED_INDIRECT_X},
		{0xA5, "LDA", ZERO_PAGE},
		{0xA9, "LDA", IMMEDIATE},
		{0xAD, "LDA", ABSOLUTE},
		{0xB1, "LDA", INDIRECT_INDEXED_Y},
		{0xB5, "LDA", ZERO_PAGE_INDEXED_X},
		{0xB9, "LDA", ABSOLUTE_INDEXED_Y},
		{0xBD, "LDA", ABSOLUTE_INDEXED_X},

		{0xA2, "LDX", IMMEDIATE},
		{0xA6, "LDX", ZERO_PAGE},
		{0xAE, "LDX", ABSOLUTE},
		{0xB6, "LDX", ZERO_PAGE_INDEXED_Y},
		{0xBE, "LDX", ABSOLUTE_INDEXED_Y},

		{0xA0, "LDY", IMMEDIATE},
		{0xA4, "LDY", ZERO_PAGE},
		{0xAC, "LDY", ABSOLUTE},
		{0xB4, "LDY", ZERO_PAGE_INDEXED_X},
		{0xBC, "LDY", ABSOLUTE_INDEXED_X},

		{0x46, "LSR", ZERO_PAGE },
		{0x4A, "LSR", ACCUMULATOR},
		{0x4E, "LSR", ABSOLUTE},
		{0x56, "LSR", ZERO_PAGE_INDEXED_X},
		{0x5E, "LSR", ABSOLUTE_INDEXED_X},

		{0xEA, "NOP", IMPLIED},

		{0x01, "ORA", INDEXED_INDIRECT_X},
		{0x05, "ORA", ZERO_PAGE},
		{0x09, "ORA", IMMEDIATE},
		{0x0D, "ORA", ABSOLUTE},
		{0x11, "ORA", INDIRECT_INDEXED_Y},
		{0x15, "ORA", ZERO_PAGE_INDEXED_X},
		{0x19, "ORA", ABSOLUTE_INDEXED_Y},
		{0x1D, "ORA", ABSOLUTE_INDEXED_X},

		{0x48, "PHA", IMPLIED},

		{0x08, "PHP", IMPLIED},

		{0x68, "PLA", IMPLIED},

		{0x28, "PLP", IMPLIED},

		{0x26, "ROL", ZERO_PAGE},
		{0x2A, "ROL", ACCUMULATOR},
		{0x2E, "ROL", ABSOLUTE},
		{0x36, "ROL", ZERO_PAGE_INDEXED_X},
		{0x3E, "ROL", ABSOLUTE_INDEXED_X},

		{0x66, "ROR", ZERO_PAGE},
		{0x6A, "ROR", ACCUMULATOR},
		{0x6E, "ROR", ABSOLUTE},
		{0x76, "ROR", ZERO_PAGE_INDEXED_X},
		{0x7E, "ROR", ABSOLUTE_INDEXED_X},

		{0x40, "RTI", IMPLIED},

		{0x60, "RTS", IMPLIED},

		{0xE1, "SBC", INDEXED_INDIRECT_X},
		{0xE5, "SBC", ZERO_PAGE},
		{0xE9, "SBC", IMMEDIATE},
		{0xED, "SBC", ABSOLUTE},
		{0xF1, "SBC", INDIRECT_INDEXED_Y},
		{0xF5, "SBC", ZERO_PAGE_INDEXED_X},
		{0xF9, "SBC", ABSOLUTE_INDEXED_Y},
		{0xFD, "SBC", ABSOLUTE_INDEXED_X},

		{0x38, "SEC", IMPLIED},

		{0xF8, "SED", IMPLIED},

		{0x78, "SEI", IMPLIED},

		{0x81, "STA", INDEXED_INDIRECT_X},
		{0x85, "STA", ZERO_PAGE},
		{0x8D, "STA", ABSOLUTE},
		{0x91, "STA", INDIRECT_INDEXED_Y},
		{0x95, "STA", ZERO_PAGE_INDEXED_X},
		{0x99, "STA", ABSOLUTE_INDEXED_Y},
		{0x9D, "STA", ABSOLUTE_INDEXED_X},

		{0x86, "STX", ZERO_PAGE},
		{0x8E, "STX", ABSOLUTE},
		{0x96, "STX", ZERO_PAGE_INDEXED_Y},

		{0x84, "STY", ZERO_PAGE},
		{0x8C, "STY", ABSOLUTE},
		{0x94, "STY", ZERO_PAGE_INDEXED_X},

		{0xAA, "TAX", IMPLIED},

		{0xA8, "TAY", IMPLIED},

		{0xBA, "TSX", IMPLIED},

		{0x8A, "TXA", IMPLIED},

		{0x9A, "TXS", IMPLIED},

		{0x98, "TYA", IMPLIED},
	};